//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mbu_spectransEntities : DbContext
    {
        private static mbu_spectransEntities _context;
        public static mbu_spectransEntities GetContext()
        {
            if (_context == null)
                _context = new mbu_spectransEntities();

            return _context;
        }
        public mbu_spectransEntities()
            : base("name=mbu_spectransEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<zakazy> zakazy { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
    }
}
